In [3]:
 # Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import pandas as pd
from pathlib import Path

In [9]:
crimes_file_path = Path(".\Resources\crime.csv")
crime_df = pd.read_csv(crimes_file_path, encoding='cp1252')
crime_df.head()

,incident_id,offense_id,offense_code,offense_code_extension,offense_type_id,offense_category_id,first_occurrence_date,last_occurrence_date,reported_date,incident_address,geo_x,geo_y,geo_lon,geo_lat,district_id,precinct_id,neighborhood_id,is_crime,is_traffic,victim_count
0,202268791,202268791299900,2999,0,criminal-mischief-other,public-disorder,2/10/2022 2:50:00 AM,NaN,2/10/2022 3:16:00 AM,1107 N SANTA FE DR,3140929.0,1692612.0,-104.998910,39.733957,1,123,lincoln-park,1,0,1
1,2021387586,2021387586299900,2999,0,criminal-mischief-other,public-disorder,7/7/2021 9:02:00 PM,NaN,7/8/2021 12:55:00 AM,815 16TH ST,3142470.0,1697098.0,-104.993342,39.746248,6,611,cbd,1,0,1
2,2020641486,2020641486299900,2999,0,criminal-mischief-other,public-disorder,10/29/2020 1:30:00 AM,NaN,10/29/2020 4:31:00 AM,4745 N FEDERAL BLVD,3133352.0,1710396.0,-105.025520,39.782888,1,111,berkeley,1,0,1
3,2018612468,2018612468299900,2999,0,criminal-mischief-other,public-disorder,9/6/2018 5:00:00 PM,9/6/2018 11:00:00 PM,9/7/2018 9:58:00 AM,65 S FEDERAL BLVD,3133534.0,1685797.0,-105.025330,39.715357,4,411,barnum,1,0,1
4,2020293614,2020293614299900,2999,0,criminal-mischief-other,public-disorder,5/8/2020 5:00:00 AM,5/8/2020 6:30:00 PM,5/13/2020 10:00:00 AM,12295 E ALBROOK DR,3184065.0,1710782.0,-104.845074,39.783082,5,521,montbello,1,0,1

In [31]:
offenses_file_path = Path(".\Resources\offense_codes.csv")
offenses_df = pd.read_csv(offenses_file_path, encoding='cp1252')
offenses_df.head()

,OBJECTID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_TYPE_NAME,OFFENSE_CATEGORY_ID,OFFENSE_CATEGORY_NAME,IS_CRIME,IS_TRAFFIC
0,1,2804,1,stolen-property-possession,Possession of stolen property,all-other-crimes,All Other Crimes,1,0
1,2,2804,2,fraud-possess-financial-device,Possession of a financial device,all-other-crimes,All Other Crimes,1,0
2,3,2901,0,damaged-prop-bus,Damaged business property,public-disorder,Public Disorder,1,0
3,4,2902,0,criminal-mischief-private,Criminal mischief to private property,public-disorder,Public Disorder,1,0
4,5,2903,0,criminal-mischief-public,Criminal mischief to public property,public-disorder,Public Disorder,1,0

In [12]:
crime_df = crime_df.drop(columns=['incident_id', 'offense_id', 'first_occurrence_date', 'last_occurrence_date', 'geo_x', 'geo_y', 
                       'is_crime', 'is_traffic'])
crime_df.head()

,offense_code,offense_code_extension,offense_type_id,offense_category_id,reported_date,incident_address,geo_lon,geo_lat,district_id,precinct_id,neighborhood_id,victim_count
0,2999,0,criminal-mischief-other,public-disorder,2/10/2022 3:16:00 AM,1107 N SANTA FE DR,-104.998910,39.733957,1,123,lincoln-park,1
1,2999,0,criminal-mischief-other,public-disorder,7/8/2021 12:55:00 AM,815 16TH ST,-104.993342,39.746248,6,611,cbd,1
2,2999,0,criminal-mischief-other,public-disorder,10/29/2020 4:31:00 AM,4745 N FEDERAL BLVD,-105.025520,39.782888,1,111,berkeley,1
3,2999,0,criminal-mischief-other,public-disorder,9/7/2018 9:58:00 AM,65 S FEDERAL BLVD,-105.025330,39.715357,4,411,barnum,1
4,2999,0,criminal-mischief-other,public-disorder,5/13/2020 10:00:00 AM,12295 E ALBROOK DR,-104.845074,39.783082,5,521,montbello,1

In [33]:
offenses_df = offenses_df.drop(columns=['OBJECTID', 'OFFENSE_CATEGORY_NAME', 'IS_CRIME', 'IS_TRAFFIC'])
offenses_df.head()

,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_TYPE_NAME,OFFENSE_CATEGORY_ID
0,2804,1,stolen-property-possession,Possession of stolen property,all-other-crimes
1,2804,2,fraud-possess-financial-device,Possession of a financial device,all-other-crimes
2,2901,0,damaged-prop-bus,Damaged business property,public-disorder
3,2902,0,criminal-mischief-private,Criminal mischief to private property,public-disorder
4,2903,0,criminal-mischief-public,Criminal mischief to public property,public-disorder

In [14]:
crime_df.isna().sum()

offense_code                  0
offense_code_extension        0
offense_type_id               0
offense_category_id           0
reported_date                 0
incident_address          15503
geo_lon                   15769
geo_lat                   15769
district_id                  57
precinct_id                   0
neighborhood_id             689
victim_count                  0
dtype: int64

In [36]:
column_names = list(offenses_df.columns.values)
column_names

['OFFENSE_CODE',
 'OFFENSE_CODE_EXTENSION',
 'OFFENSE_TYPE_ID',
 'OFFENSE_TYPE_NAME',
 'OFFENSE_CATEGORY_ID']

In [37]:
lc_n = [x.lower() for x in column_names]
    
lc_n

['offense_code',
 'offense_code_extension',
 'offense_type_id',
 'offense_type_name',
 'offense_category_id']

In [38]:
offenses_df.columns=lc_n
offenses_df.head()

,offense_code,offense_code_extension,offense_type_id,offense_type_name,offense_category_id
0,2804,1,stolen-property-possession,Possession of stolen property,all-other-crimes
1,2804,2,fraud-possess-financial-device,Possession of a financial device,all-other-crimes
2,2901,0,damaged-prop-bus,Damaged business property,public-disorder
3,2902,0,criminal-mischief-private,Criminal mischief to private property,public-disorder
4,2903,0,criminal-mischief-public,Criminal mischief to public property,public-disorder

In [28]:
offenses_df.dtypes

offense_type_id            int64
offense_code               int64
offense_type_name         object
offense_code_extension    object
offense_category_id       object
dtype: object

In [29]:
crime_df.dtypes

offense_code                int64
offense_code_extension      int64
offense_type_id            object
offense_category_id        object
reported_date              object
incident_address           object
geo_lon                   float64
geo_lat                   float64
district_id                object
precinct_id                 int64
neighborhood_id            object
victim_count                int64
dtype: object

In [39]:
merged_df = pd.merge(crime_df, offenses_df,  how='outer', left_on=['offense_code','offense_code_extension','offense_type_id',
                                                                   'offense_category_id'], right_on=['offense_code',
                                                                                                    'offense_code_extension',
                                                                                                     'offense_type_id',
                                                                                                     'offense_category_id']) 
merged_df.head()

,offense_code,offense_code_extension,offense_type_id,offense_category_id,reported_date,incident_address,geo_lon,geo_lat,district_id,precinct_id,neighborhood_id,victim_count,offense_type_name
0,2999,0,criminal-mischief-other,public-disorder,2/10/2022 3:16:00 AM,1107 N SANTA FE DR,-104.998910,39.733957,1,123.0,lincoln-park,1.0,Criminal mischief - other
1,2999,0,criminal-mischief-other,public-disorder,7/8/2021 12:55:00 AM,815 16TH ST,-104.993342,39.746248,6,611.0,cbd,1.0,Criminal mischief - other
2,2999,0,criminal-mischief-other,public-disorder,10/29/2020 4:31:00 AM,4745 N FEDERAL BLVD,-105.025520,39.782888,1,111.0,berkeley,1.0,Criminal mischief - other
3,2999,0,criminal-mischief-other,public-disorder,9/7/2018 9:58:00 AM,65 S FEDERAL BLVD,-105.025330,39.715357,4,411.0,barnum,1.0,Criminal mischief - other
4,2999,0,criminal-mischief-other,public-disorder,5/13/2020 10:00:00 AM,12295 E ALBROOK DR,-104.845074,39.783082,5,521.0,montbello,1.0,Criminal mischief - other

In [40]:
merged_df.to_csv('crimes_and_offenses.csv', index=False)